(source gnu)
(source melpa)
(source marmalade)

;;; General editing, programming and project tools
(depends-on "perspective")
(depends-on "projectile")
(depends-on "highlight-indentation")
(depends-on "ag")
(depends-on "wgrep")
(depends-on "wgrep-ag")
(depends-on "markdown-mode")
(depends-on "feature-mode")
(depends-on "restclient")
(depends-on "dired-filter")
(depends-on "dired-subtree")
(depends-on "dired-ranger")
(depends-on "dired-narrow")
(depends-on "direx")
(depends-on "git-link")

;; General emacs tools
(depends-on "evil")
(depends-on "expand-region")
(depends-on "ecb")
(depends-on "tabulated-list")
(depends-on "twittering-mode")
(depends-on "git-gutter")
(depends-on "hydra")
(depends-on "browse-kill-ring")
(depends-on "discover-my-major")

;; Libraries
(depends-on "f")    ; Directory and file api
(depends-on "dash") ; Modern list library

;; Extra
(depends-on "zone-nyan") ; Nyan cat zone
